# Generated by Django 4.2.4 on 2023-08-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "MyModel",
                "verbose_name_plural": "MyModels",
            },
        ),
    ]
